name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  sanity-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.8"
    - name: Install system dependencies
      run: |
        set -ex
        sudo apt update
        sudo apt install ffmpeg libsndfile1-dev portaudio19-dev
        pip install pipenv --upgrade
    - name: Install Python dependencies
      run: make dev-deps
    - name: Run type checker
      run: make type-check
    - name: Run linters
      run: make style-check
    - name: Verify examples
      run: make examples

